@extends('layouts.master', ['page' => 'privacy', 'title' => 'Privacy Policy'])

@section('content')
    <main class="page">
        <div class="container">
            <h1>Privacy Policy</h1>
            <h4><em>Your privacy is critically important to us. At AbsoluteCraft we have a few fundamental principles:</em></h4>
            <ul>
                <li>We don't ask you for personal information unless we truly need it.</li>
                <li>We don't share your personal information with anyone except to comply with the law, develop our products, or protect our rights.</li>
                <li>We don't store personal information on our servers unless required for the on-going operation of one of our services.</li>
            </ul><br>
            <p>Below is our privacy policy which incorporates these goals:</p>
            <p>If you have questions about deleting or correcting your personal data please contact us.</p>
            <p>It is AbsoluteCraft's policy to respect your privacy regarding any information we may collect on https://absolutecraft.co.uk</p>
            <h3>Website Visitors</h3>
            <p>Like most website operators, AbsoluteCraft collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. AbsoluteCraft's purpose in collecting non-personally identifying information is to better understand how AbsoluteCraft's visitors use its website. From time to time, AbsoluteCraft may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</p>
            <h3>Gathering of Personally-Identifying Information</h3>
            <p>Certain visitors to AbsoluteCraft's websites choose to interact with AbsoluteCraft in ways that require AbsoluteCraft to gather personally-identifying information. The amount and type of information that AbsoluteCraft gathers depends on the nature of the interaction. For example, we ask visitors who sign up to provide a username and email address.AbsoluteCraft collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor's interaction with AbsoluteCraft. AbsoluteCraft does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</p>
            <h3>Aggregated Statistics</h3>
            <p>AbsoluteCraft may collect statistics about the behavior of visitors to its websites. For instance, AbsoluteCraft may monitor the most popular posts on the site. AbsoluteCraft may display this information publicly or provide it to others. However, AbsoluteCraft does not disclose personally-identifying information other than as described below.</p>
            <h3>Protection of Certain Personally-Identifying Information</h3>
            <p>AbsoluteCraft discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on AbsoluteCraft's behalf or to provide services available at http://absolutecraft.co.uk, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using AbsoluteCraft's websites, you consent to the transfer of such information to them. AbsoluteCraft will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, AbsoluteCraft discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when AbsoluteCraft believes in good faith that disclosure is reasonably necessary to protect the property or rights of AbsoluteCraft, third parties or the public at large. If you are a registered user of the AbsoluteCraft website and have supplied your email address, AbsoluteCraft may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what's going on with AbsoluteCraft and our products. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. AbsoluteCraft takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>
            <h3>Cookies</h3>
            <p>A cookie is a string of information that a website stores on a visitor's computer, and that the visitor's browser provides to the website each time the visitor returns. AbsoluteCraft uses cookies to help AbsoluteCraft identify and track visitors, their usage of AbsoluteCraft website, and their website access preferences. AbsoluteCraft visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using http://absolutecraft.co.uk, with the drawback that certain features of the site may not function properly without the aid of cookies.</p>
            <h3>Business Transfers</h3>
            <p>If AbsoluteCraft, or substantially all of its assets, were acquired, or in the event that AbsoluteCraft goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of AbsoluteCraft may continue to use your personal information as set forth in this policy.</p>
            <h3>Ads</h3>
            <p>Ads appearing on any of our websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by AbsoluteCraft and does not cover the use of cookies by any advertisers.</p>
            <h3>Privacy Policy Changes</h3>
            <p>Although most changes are likely to be minor, AbsoluteCraft may change its Privacy Policy from time to time, and in AbsoluteCraft's sole discretion. AbsoluteCraft encourages visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.</p><br>
            <p style="color: #999;">Adapted from <a href="https://automattic.com/privacy" target="_blank" style="color: #999; text-decoration: none;">Automattic</a></p>
        </div>
    </main>
@stop
